### ISSUE TITLE
Handoff between real-time and historical processing

### ISSUE THREAD

**Issue by Ishatt** [near/queryapi#216]
Description

Problem:

Currently we do not coordinate between real-time and historical processing, indexers can run on blocks out of order. 

See Confluence pages

See [Real-time to Historical communication](https://pagodaplatform.atlassian.net/wiki/spaces/DAT/pages/333545513/Real-time+to+Historical+communication) for architectural concerns.

Proposed Solutions:

Append real-time blocks to be processed to the processing queue of the historical thread.

After the move to Redis we could store a redis flag for each function for historical_backfill_in_progress . When this is set at the start of historical backfill, real-time processing can skip processing until both the flag is cleared and the historical queue is empty. Once the historical queue has been filled the flag can be cleared.
```[tasklist]
### Linked Issues
- [ ] https://github.com/near/queryapi/issues/198
```

```[tasklist]
### Relates to
```

**Comment by roshaans** [comment]
@ailisp would like to create a "sql join query" in query-api, but is unable to do so without Hasura foriegn-key relationships which he is unable to do as QueryAPI currently processes historical backfill in parallel with real-time blocks and in order to create forign-key relationships, you have to impose an order of insertions

object X references object Y, but X can be inserted before Y that result in foreign key constraint violation.

**Comment by morgsmccauley** [comment]
One way to solve this is for each indexer to have their own 'real time' block process, rather than the shared one we have now. This would make the handover much simpler, as it could just 'start' after historical has completed.
