### ISSUE TITLE
Reduce duplicate Lake requests across dedicated streams

### ISSUE THREAD

**Issue by morgsmccauley** [near/queryapi#419]
After https://github.com/near/queryapi/issues/418, each Indexer will have it's own dedicated 'real-time' stream, creating many duplicate requests to NEAR Lake. These duplicate requests should be reduced.

One approach is to use a singleton Lake client, which ensures only a single request is sent per block, and awaits the existing one otherwise. But I'm not entirely sure how this can be implemented.

**Comment by morgsmccauley** [comment]
Dumping some context here before I go on leave:

The actual lake requests are made within a different crate (`near-lake-framework`), therefore caching these is not that straight forward.

`near-lake-framework` accepts an [aws_sdk_s3::config::Config](https://docs.rs/aws-sdk-s3/1.16.0/aws_sdk_s3/config/struct.Config.html) struct, and I was hoping we could somehow configure the HTTP client used by the AWS SDK so that we could intercept/short-circuit the requests, but this doesn't seem possible. The [http_client](https://docs.rs/aws-sdk-s3/1.16.0/aws_sdk_s3/config/struct.Builder.html#method.http_client) can be set, but afaik, this only configures the `Connector`, which defines how connections are established, and doesn't provide access to the requests/responses themselves. [interceptors](https://docs.rs/aws-sdk-s3/1.16.0/aws_sdk_s3/config/struct.Builder.html#method.interceptor) don't seem like they can help either, they just provide hooks in to the request/response lifecycle, and don't allow for short-circuiting. There may be a way to configure AWS to achieve what we want, but it seemed really hacky/low-level.

An alternate approach I toyed with was updating `near-lake-framework` so that an `S3Client` could be passed instead of `S3Config`. That way we'd have direct control over the requests made to S3. `near-lake-framework` already has an [S3Client interface](https://github.com/near/near-lake-framework-rs/blob/554c4939b3713953aaab75a78831e94b9c009e11/src/s3_fetchers.rs#L6), so we could define a shared `impl` on the QueryAPI aside, with cache built in, and then make `near-lake-framework` use it.

I didn't get too far with the above approach - I still need to figure out how to make the client configurable in a non-intrusive way.

**Comment by darunrs** [comment]
Just an update on this task. Eduardo and I were discussing approaches to improve overall latency. One suggestion Eduardo brought up which I think has merit is having a standalone process in block streamer which maintains some amount of time of blocks (e.g. 1 hour) in Redis or ScyllaDB. By doing so, all real time indexers benefit from it since both Block Streamer and Runner can fetch the block from cache rather than downloading it (Right now due to 60sec caching only Block Streamer still downloads the blocks). 

Curious to hear @morgsmccauley's thoughts on the approach. This doesn't solve historical backfill problems but it does at least eliminate common replication problems.

**Comment by pkudinov** [comment]
Reopening after rollback from prod
