### ISSUE TITLE
Firecracker PoC

### ISSUE THREAD

**Issue by pkudinov** [near/queryapi#732]

**Comment by morgsmccauley** [comment]
Finally got Firecracker working, I've provided an update below. Will close this for now as it is de-prioritised, but hopefully this context allows it to be easily picked up again.

### :computer: Current state
- GCE instance ([morgs-firecracker-vm](https://console.cloud.google.com/compute/instancesDetail/zones/europe-west1-b/instances/morgs-firecracker-vm?project=pagoda-data-stack-dev)) setup in GCP with nested virtualisation enabled. In hindsight I should have used bare-metal.
- Firecracker installed and single microVM initialised (8 vcpu, 16gb memory)
- VM image created from "Standalone" Runner (single indexer on main thread outside of VM) and booted within microVM
- `darunrs.near/bitmap_v5` Indexer running within Standalone Runner
- Traces exported to GCP: `morgs.near/katacontainers` (docker standalone), `morgs.near/firecracker`. It may be a little confusing as there are some failures intermingled, I am intentionally throwing an error on the Runner side, but on the standalone side the code is hard-coded.

### :rocket: Performance Comparison
To compare, I started the Firecracker Indexer from the current block of the existing `bitmap_v5` Indexer. There will always be some sort of offset though so it's hard to make a concrete comparison.

Metrics are being exported from Firecracker and can be viewed [here](https://nearinc.grafana.net/d/ddm8rm1a4bsaof/firecracker?orgId=1&refresh=5s&from=now-3h&to=now). The current bitmap Indexer can be found [here](https://nearinc.grafana.net/d/ddga70ci0e03ka/indexer?orgId=1&var-env=dev&var-Indexer=darunrs.near%2Fbitmap_v5&from=now-12h&to=now). Looking back at the past 12 hours, where the Indexers should have been working over the same data, Firecracker has:
- :chart_with_upwards_trend: A smaller max execution duration - 350ms vs 650ms
- :chart_with_downwards_trend: A smaller max BPS - 8 vs 12.5

**Overall it looks slower**, which is hard to believe. It seems Firecracker's biggest benefit is on its low startup times, with its runtime performance comparable to containers, so maybe there isn't much difference. But I would have expected Standalone Runner (No-worker threads/No-VM) to make some impact. Again, it's hard to make a fair comparison here so I will continue to work on this.

### :warning: Concerns
- **Firecracker is really hard to work with**, automating it is going to be even harder. It is really low-level, so it may be due to my unfamiliarity with sysadmin tasks, but as the one potentially maintaining it, it is still a concern
- **Firecracker can't run on MacOS**, so local development will be tricky
- **We still need code-level sandboxing**, i.e. we may not be able to remove the VM - the code which wraps the Indexer code requires various secrets which should be isolated from the Indexer. Removing pre-fetch from Runner will help this since we can remove AWS keys, but we'll still have Hasura/Postgres secrets. There are probably ways to architect this differently to allow us to remove the VM.

### :ladder: Next steps
- Continue with the performance comparison:
  - Ensure I am measuring the Indexers over the same data set - forking `bitmap_v5` will actually make this easier
  - Setup another Standalone Runner instance running in Docker - allowing us to compare apples with apples
  - Ensure all versions are using the same PG pooling, either disable pg-bouncer for Runner, or enable it for Firecracker, the former is probably easier.
- Investigate alternatives
  - While looking in to Firecracker, I came across [Katacontainers](https://katacontainers.io/), which is a container runtime that provides VM level security. This would provide the same security benefits of Firecracker (and can actually run on top Firecracker), with hopefully comparable performance. This would also be more ergonomic as it would integrate nicely with our existing container workflow, and can be easily plugged in to Kubernetes providing horizontal scalability.
- Use bare-metal instances. Setting these up in GCP isn't as trivial as it is in AWS, we need to reach out directly to the GCP team.
